### ISSUE TITLE
examples of unit test and intregration with CI/code coverage services

### ISSUE THREAD

**Issue by sciamano** [SecUSo/privacy-friendly-app-example#4]
very helpful "app", really like the idea. Will be greate if you can provide examples of unit tests for the code as well an integration with popular CI services: Travis CI, circleCI, codecov, coverity.

**Comment by Yonjuni** [comment]
Thanks for the comment. The app just serves as a design demo mainly for students who are developing Privacy Friendly Apps. We did not include Unit Tests are there already is good "self-updating" documentation available.
It furthermore is not intended to include the CI services in the future as we wish to keep the app as simple as possible.
